name: Build and Deploy to Dedicated Branch

on:
  push:
    branches:
      - main # Or your main development branch

jobs:
  build-and-deploy:
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to get an OIDC token
    runs-on: ubuntu-latest
    environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v4

      # Build step (replace with your build commands)
      - name: Build Website
        run: |
          mkdir ./build && cp -r ./game/* build/ && cat ./engine/*.js > ./build/engine.js && cat ./engine/*.css > ./build/engine.css

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './build' # Replace with the actual path to your built site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

