name: Build and Deploy to Dedicated Branch

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v3

      - name: Build Website
        run: |
          mkdir -p ./build
          if [ -d "./game" ]; then
            cp -r ./game/* build/ || echo "Warning: Could not copy game files"
          else
            echo "Warning: game directory not found"
          fi
          if [ -d "./engine" ]; then
            find ./engine -name "*.js" | xargs cat > ./build/engine.js || echo "Warning: No JS files found"
            find ./engine -name "*.css" | xargs cat > ./build/engine.css || echo "Warning: No CSS files found" 
          else
            echo "Warning: engine directory not found"
            touch ./build/engine.js ./build/engine.css
          fi

  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to get an OIDC token
    environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - name: Upload
        uses: actions/upload-pages-artifact@v2
        with:
          path: "build/" 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3

